"""Reusable harness components for production-style agent experiments."""

from .context_manager import (
    AgentSessionState,
    COMPRESSION_SUMMARY_KEYS,
    COMPRESSION_TRIGGERS,
    CompressionRecord,
    CompressionSummary,
    ContextManager,
    SessionSummary,
    TaskPack,
)
from .dynamic_task_planner import DynamicTaskPlanner, TaskTemplate
from .frontend_generator import (
    FrontendGenerator,
    FrontendProjectSpec,
    GeneratedFrontendProject,
    REQUIRED_FRONTEND_FILES,
)
from .failure_feedback import (
    AffectedFile,
    FailureClassifier,
    FailureDigest,
    FailureEvidence,
    FAILURE_ERROR_TYPES,
)
from .model_gateway import (
    DEFAULT_ROLE_POLICIES,
    AgentRole,
    GatewayCallRecord,
    ModelGateway,
    ModelGatewayError,
    ModelGatewayResponse,
    ModelPolicy,
    TokenBudgetExceeded,
    default_role_policies,
)
from .repo_scanner import PackageFacts, RepoFacts, RepoScanner
from .requirement_analyzer import LLMRequirementAnalyzer, RequirementAnalyzer, RequirementSpec
from .sandbox_runner import (
    BrowserProfile,
    BrowserViewport,
    DockerSandboxRunner,
    SANDBOX_STATUSES,
    SandboxExecutionResult,
    SandboxRun,
    TestCommand,
    TestProfile,
    frontend_ui_component_profile,
)
from .task_planner import (
    AgentTask,
    TaskPlan,
    TaskPlanner,
    TASK_STATUSES,
)
from .verifier import (
    BrowserResult,
    CommandResult,
    VERIFICATION_STATUSES,
    VerificationReport,
    Verifier,
)

__all__ = [
    "AgentSessionState",
    "AgentRole",
    "AgentTask",
    "AffectedFile",
    "BrowserProfile",
    "BrowserResult",
    "BrowserViewport",
    "COMPRESSION_SUMMARY_KEYS",
    "COMPRESSION_TRIGGERS",
    "CommandResult",
    "CompressionRecord",
    "CompressionSummary",
    "ContextManager",
    "DEFAULT_ROLE_POLICIES",
    "DockerSandboxRunner",
    "DynamicTaskPlanner",
    "FAILURE_ERROR_TYPES",
    "FailureClassifier",
    "FailureDigest",
    "FailureEvidence",
    "FrontendGenerator",
    "FrontendProjectSpec",
    "GatewayCallRecord",
    "GeneratedFrontendProject",
    "ModelGateway",
    "ModelGatewayError",
    "ModelGatewayResponse",
    "ModelPolicy",
    "LLMRequirementAnalyzer",
    "PackageFacts",
    "REQUIRED_FRONTEND_FILES",
    "RepoFacts",
    "RepoScanner",
    "RequirementAnalyzer",
    "RequirementSpec",
    "SANDBOX_STATUSES",
    "SessionSummary",
    "SandboxExecutionResult",
    "SandboxRun",
    "TASK_STATUSES",
    "TaskPack",
    "TaskTemplate",
    "TestCommand",
    "TestProfile",
    "TaskPlan",
    "TaskPlanner",
    "TokenBudgetExceeded",
    "VERIFICATION_STATUSES",
    "VerificationReport",
    "Verifier",
    "default_role_policies",
    "frontend_ui_component_profile",
]
